//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Module.
        /// </summary>
        internal static string ActiveModule {
            get {
                return ResourceManager.GetString("ActiveModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Record.
        /// </summary>
        internal static string AddNewRecord {
            get {
                return ResourceManager.GetString("AddNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        internal static string AfterPageText {
            get {
                return ResourceManager.GetString("AfterPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Types.
        /// </summary>
        internal static string AllowanceTypes {
            get {
                return ResourceManager.GetString("AllowanceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources Solution.
        /// </summary>
        internal static string ApplicationModule {
            get {
                return ResourceManager.GetString("ApplicationModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AionHR.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string ArabicLanguage {
            get {
                return ResourceManager.GetString("ArabicLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Day.
        /// </summary>
        internal static string AttendanceDay {
            get {
                return ResourceManager.GetString("AttendanceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Schedule.
        /// </summary>
        internal static string AttendanceSchedule {
            get {
                return ResourceManager.GetString("AttendanceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string BeforePageText {
            get {
                return ResourceManager.GetString("BeforePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometric Devices.
        /// </summary>
        internal static string BiometricDevices {
            get {
                return ResourceManager.GetString("BiometricDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Management.
        /// </summary>
        internal static string CaseManagement {
            get {
                return ResourceManager.GetString("CaseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        internal static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        internal static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Cases.
        /// </summary>
        internal static string CasesLeaf {
            get {
                return ResourceManager.GetString("CasesLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Levels.
        /// </summary>
        internal static string CertificateLevels {
            get {
                return ResourceManager.GetString("CertificateLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string CollapsePanel {
            get {
                return ResourceManager.GetString("CollapsePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string ColumnsText {
            get {
                return ResourceManager.GetString("ColumnsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Structure.
        /// </summary>
        internal static string CompanyStructure {
            get {
                return ResourceManager.GetString("CompanyStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2017 AionHR. All rights reserved..
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayFriday.
        /// </summary>
        internal static string DayFriday {
            get {
                return ResourceManager.GetString("DayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayMonday.
        /// </summary>
        internal static string DayMonday {
            get {
                return ResourceManager.GetString("DayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day - Month - Year.
        /// </summary>
        internal static string DayMonthYear {
            get {
                return ResourceManager.GetString("DayMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaySaturday.
        /// </summary>
        internal static string DaySaturday {
            get {
                return ResourceManager.GetString("DaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaySunday.
        /// </summary>
        internal static string DaySunday {
            get {
                return ResourceManager.GetString("DaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayThursday.
        /// </summary>
        internal static string DayThursday {
            get {
                return ResourceManager.GetString("DayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayTuesday.
        /// </summary>
        internal static string DayTuesday {
            get {
                return ResourceManager.GetString("DayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Types.
        /// </summary>
        internal static string DayTypes {
            get {
                return ResourceManager.GetString("DayTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayWednesday.
        /// </summary>
        internal static string DayWednesday {
            get {
                return ResourceManager.GetString("DayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day- Year - Month.
        /// </summary>
        internal static string DayYearMonth {
            get {
                return ResourceManager.GetString("DayYearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected records ?.
        /// </summary>
        internal static string DeleteManyRecord {
            get {
                return ResourceManager.GetString("DeleteManyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected record ?.
        /// </summary>
        internal static string DeleteOneRecord {
            get {
                return ResourceManager.GetString("DeleteOneRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying Records {0} - {1} of {2}.
        /// </summary>
        internal static string DisplayMsg {
            get {
                return ResourceManager.GetString("DisplayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisions.
        /// </summary>
        internal static string Divisions {
            get {
                return ResourceManager.GetString("Divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Record.
        /// </summary>
        internal static string EditWindowsTitle {
            get {
                return ResourceManager.GetString("EditWindowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Files.
        /// </summary>
        internal static string EmployeeFiles {
            get {
                return ResourceManager.GetString("EmployeeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Employee.
        /// </summary>
        internal static string EmployeeLeaf {
            get {
                return ResourceManager.GetString("EmployeeLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record to Display.
        /// </summary>
        internal static string EmptyMsg {
            get {
                return ResourceManager.GetString("EmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitlement Deduction.
        /// </summary>
        internal static string EntitlementDeduction {
            get {
                return ResourceManager.GetString("EntitlementDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting Record,try again later..
        /// </summary>
        internal static string ErrorDeletingRecord {
            get {
                return ResourceManager.GetString("ErrorDeletingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Operation, Try again Later !.
        /// </summary>
        internal static string ErrorOperation {
            get {
                return ResourceManager.GetString("ErrorOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving this Record..
        /// </summary>
        internal static string ErrorSavingRecord {
            get {
                return ResourceManager.GetString("ErrorSavingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Updating this Record..
        /// </summary>
        internal static string ErrorUpdatingRecord {
            get {
                return ResourceManager.GetString("ErrorUpdatingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string ExpandPanel {
            get {
                return ResourceManager.GetString("ExpandPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name , Last Name.
        /// </summary>
        internal static string FirstNameLastName {
            get {
                return ResourceManager.GetString("FirstNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name, Middle Name, Last Name.
        /// </summary>
        internal static string FirstNameMiddleNameLastName {
            get {
                return ResourceManager.GetString("FirstNameMiddleNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string FirstText {
            get {
                return ResourceManager.GetString("FirstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string FridayText {
            get {
                return ResourceManager.GetString("FridayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        internal static string LanguageSwitch {
            get {
                return ResourceManager.GetString("LanguageSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name, First Name.
        /// </summary>
        internal static string LastNameFirstName {
            get {
                return ResourceManager.GetString("LastNameFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string LastText {
            get {
                return ResourceManager.GetString("LastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Management.
        /// </summary>
        internal static string LeaveManagement {
            get {
                return ResourceManager.GetString("LeaveManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveTypes.
        /// </summary>
        internal static string LeaveTypes {
            get {
                return ResourceManager.GetString("LeaveTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Search.
        /// </summary>
        internal static string LiveSearch {
            get {
                return ResourceManager.GetString("LiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Failed.
        /// </summary>
        internal static string LoadFailed {
            get {
                return ResourceManager.GetString("LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is mandatory !.
        /// </summary>
        internal static string MandatoryField {
            get {
                return ResourceManager.GetString("MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Deleted Successfully.
        /// </summary>
        internal static string ManyRecordDeletedSucc {
            get {
                return ResourceManager.GetString("ManyRecordDeletedSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match(es) found..
        /// </summary>
        internal static string MatchFound {
            get {
                return ResourceManager.GetString("MatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string MondayText {
            get {
                return ResourceManager.GetString("MondayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month - Day - Year.
        /// </summary>
        internal static string MonthDayYear {
            get {
                return ResourceManager.GetString("MonthDayYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month - Year - Day.
        /// </summary>
        internal static string MonthYearDay {
            get {
                return ResourceManager.GetString("MonthYearDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalities.
        /// </summary>
        internal static string Nationalities {
            get {
                return ResourceManager.GetString("Nationalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string NavigationPane {
            get {
                return ResourceManager.GetString("NavigationPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextText {
            get {
                return ResourceManager.GetString("NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PrevText {
            get {
                return ResourceManager.GetString("PrevText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted Successfully.
        /// </summary>
        internal static string RecordDeletedSucc {
            get {
                return ResourceManager.GetString("RecordDeletedSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved Successfully.
        /// </summary>
        internal static string RecordSavingSucc {
            get {
                return ResourceManager.GetString("RecordSavingSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Updated Successfully.
        /// </summary>
        internal static string RecordUpdatedSucc {
            get {
                return ResourceManager.GetString("RecordUpdatedSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        internal static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian.
        /// </summary>
        internal static string Religion0 {
            get {
                return ResourceManager.GetString("Religion0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muslim.
        /// </summary>
        internal static string Religion1 {
            get {
                return ResourceManager.GetString("Religion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jew.
        /// </summary>
        internal static string Religion2 {
            get {
                return ResourceManager.GetString("Religion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budha.
        /// </summary>
        internal static string Religion3 {
            get {
                return ResourceManager.GetString("Religion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seikh.
        /// </summary>
        internal static string Religion4 {
            get {
                return ResourceManager.GetString("Religion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindu.
        /// </summary>
        internal static string Religion5 {
            get {
                return ResourceManager.GetString("Religion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Religion6 {
            get {
                return ResourceManager.GetString("Religion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routers.
        /// </summary>
        internal static string Routers {
            get {
                return ResourceManager.GetString("Routers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string SaturdayText {
            get {
                return ResourceManager.GetString("SaturdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Management.
        /// </summary>
        internal static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Disconnected !.
        /// </summary>
        internal static string SessionDisconnected {
            get {
                return ResourceManager.GetString("SessionDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        internal static string SortAscText {
            get {
                return ResourceManager.GetString("SortAscText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sorting.
        /// </summary>
        internal static string SortClearText {
            get {
                return ResourceManager.GetString("SortClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        internal static string SortDescText {
            get {
                return ResourceManager.GetString("SortDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        internal static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string SundayText {
            get {
                return ResourceManager.GetString("SundayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        internal static string SystemDefaults {
            get {
                return ResourceManager.GetString("SystemDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        internal static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string ThursdayText {
            get {
                return ResourceManager.GetString("ThursdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Attendance.
        /// </summary>
        internal static string TimeAttendance {
            get {
                return ResourceManager.GetString("TimeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Record.
        /// </summary>
        internal static string TitleSavingError {
            get {
                return ResourceManager.GetString("TitleSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error During Saving, Try again later..
        /// </summary>
        internal static string TitleSavingErrorMessage {
            get {
                return ResourceManager.GetString("TitleSavingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Types.
        /// </summary>
        internal static string TrainingTypes {
            get {
                return ResourceManager.GetString("TrainingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        internal static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string TuesdayText {
            get {
                return ResourceManager.GetString("TuesdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Schedules.
        /// </summary>
        internal static string VacationSchedules {
            get {
                return ResourceManager.GetString("VacationSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string WednesdayText {
            get {
                return ResourceManager.GetString("WednesdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendars.
        /// </summary>
        internal static string WorkingCalendars {
            get {
                return ResourceManager.GetString("WorkingCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year - Day - Month.
        /// </summary>
        internal static string YearDayMonth {
            get {
                return ResourceManager.GetString("YearDayMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year - Month - Day.
        /// </summary>
        internal static string YearMonthDay {
            get {
                return ResourceManager.GetString("YearMonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
