//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AionHR.Web.UI.Forms.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VacationSchedules_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VacationSchedules_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AionHR.Web.UI.Forms.App_LocalResources.VacationSchedules.aspx", typeof(VacationSchedules_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Schedule Info.
        /// </summary>
        internal static string BasicInfoTabEditWindowTitle {
            get {
                return ResourceManager.GetString("BasicInfoTabEditWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Period.
        /// </summary>
        internal static string BtnAddPeriod {
            get {
                return ResourceManager.GetString("BtnAddPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Period.
        /// </summary>
        internal static string BtnRemovePeriod {
            get {
                return ResourceManager.GetString("BtnRemovePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vacation Schedule.
        /// </summary>
        internal static string EditWindowsTitle {
            get {
                return ResourceManager.GetString("EditWindowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Days.
        /// </summary>
        internal static string FieldDays {
            get {
                return ResourceManager.GetString("FieldDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Months.
        /// </summary>
        internal static string FieldFrom {
            get {
                return ResourceManager.GetString("FieldFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Months.
        /// </summary>
        internal static string FieldTo {
            get {
                return ResourceManager.GetString("FieldTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        internal static string Periods {
            get {
                return ResourceManager.GetString("Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods Tab.
        /// </summary>
        internal static string PeriodsTab {
            get {
                return ResourceManager.GetString("PeriodsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Schedules.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
