//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AionHR.Web.UI.Forms.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VacationSchedules_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VacationSchedules_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AionHR.Web.UI.Forms.App_LocalResources.VacationSchedules.aspx", typeof(VacationSchedules_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Info.
        /// </summary>
        internal static string BasicInfoTabEditWindowTitle {
            get {
                return ResourceManager.GetString("BasicInfoTabEditWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Department.
        /// </summary>
        internal static string EditWindowsTitle {
            get {
                return ResourceManager.GetString("EditWindowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Inactive?.
        /// </summary>
        internal static string FieldIsInactive {
            get {
                return ResourceManager.GetString("FieldIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Segmented Head.
        /// </summary>
        internal static string FieldIsSegmentedHead {
            get {
                return ResourceManager.GetString("FieldIsSegmentedHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string FieldParentName {
            get {
                return ResourceManager.GetString("FieldParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record ID.
        /// </summary>
        internal static string FieldRecordId {
            get {
                return ResourceManager.GetString("FieldRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string FieldReference {
            get {
                return ResourceManager.GetString("FieldReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        internal static string FieldSegmentCode {
            get {
                return ResourceManager.GetString("FieldSegmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string FieldSvFullName {
            get {
                return ResourceManager.GetString("FieldSvFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        internal static string FieldTimeZone {
            get {
                return ResourceManager.GetString("FieldTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods Tab.
        /// </summary>
        internal static string PeriodsTab {
            get {
                return ResourceManager.GetString("PeriodsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
